name: Run simple java test

on:
  workflow_dispatch:
    
jobs:
  test:
    name: Run java tests
    runs-on: windows-2019
    steps:
      # checkout the repo
      - uses: actions/checkout@v2

      # setup java8
      - name: Setup java8
        uses: actions/setup-java@v2
        with:
          distribution: temurin
          java-version: 8
      
      - name: Run Tests
        shell: bash
        run: |
          cd src/tests/
          javac
          java -ea SimpleTest
